### ISSUE TITLE
did:btcr:x705-jznz-qwvq-0uw is not resolvable

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#76]
https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5

**Comment by peacekeeper** [comment]
Should be fixed now, there was a problem with the btcd node behind uniresolver.io.

**Comment by OR13** [comment]
fixed

**Comment by gjgd** [comment]
I still see this error:
https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5
<img width="1400" alt="Screenshot 2020-01-27 at 01 04 32" src="https://user-images.githubusercontent.com/7913565/73139485-00780780-40a1-11ea-8f30-44ad5c8897cd.png">

The error message "Invalid definition: 1.1" looks related to #75 
<img width="1436" alt="Screenshot 2020-01-27 at 01 03 56" src="https://user-images.githubusercontent.com/7913565/73139477-ee966480-40a0-11ea-8706-25978f01a7de.png">

**Comment by OR13** [comment]
^ this is not the drive, this is the json-ld parsing issue... same is true for latest element dids.

**Comment by OR13** [comment]
if you resolve a btcr did that has a simple context (not an array) you probably won't see this issue.

**Comment by peacekeeper** [comment]
We looked at this on the [30 Jun 2021 Universal Resolver](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls) call, and it seems:
- The original issue here (JSON-LD 1.1 problem) should be obsolete, since the Universal Resolver should have full JSON-LD 1.1 support by now.
- The DIDs mentioned in this issue are now outdated, since the BTCR DID method has changed in the meantime (changing the bech32 format of the method-specific IDs), which means that those DIDs are actually invalid now (and the Universal Resolver correctly returns an error).

Therefore we'll close this, feel free to open new issues if there are still any problems.
